### ISSUE TITLE
Update extension to work with Chrome M55

### ISSUE THREAD

**Issue by manastungare** [manastungare/google-tasks-crx#2]
- Update `manifest_version`.
- Remove references to missing icons.
- Update `background_page`.
- Test with M55.
- Test with OAuth.

@nfultz How did you test your latest changes? Do you have a PR ready for some of the basic stuff to get this to load in M55?

**Comment by nfultz** [comment]
I just copied the code out of my extension repo, which I've been using for
about a year and a half.  I don't know what M55 is.

**Comment by manastungare** [comment]
M55 is the latest version of Chrome (version 55).

This extension, as is, doesn’t work at all, so I was wondering how you tested your latest changes.

**Comment by nfultz** [comment]
I'm still using my version from https://github.com/nfultz/googletasks,
which has been working fine for a long time.
I think the only difference at this point is manifest.json.  Mine, which is
here: https://github.com/nfultz/googletasks/blob/master/manifest.json
contains an oauth2 section with a clientID (which I don't really remember
how I got), and includes 'identity' in the permissions list.

**Comment by nfultz** [comment]
I sent you a PR.

**Comment by manastungare** [comment]
Fixed via 96d305c64b78609118ea278fe9ae3996b9927b41
